# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3
pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
    - step:
        name: Deploy to staging
        deployment: staging
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - echo "Deploying to staging environment"
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: 'nettleger'
              SERVER: '104.248.192.4'
              COMMAND: './deployBackend.sh'

